name: 'CapRover App Deploy OTP'
description: 'Deploy application to CapRover server'
branding:
  icon: 'caprover.svg'
  color: orange
inputs:
  host:
    description: 'CapRover machine url i.e., https://captain.your-domain.com'
    required: true
  password:
    description: 'CapRover admin password. Use secret for more security'
    required: true
  app:
    description: 'App name on CapRover server'
    required: true
  apptoken:
    description: 'App token to authenticate if OTP is used'
    required: false
  branch:
    description: 'Branch to be deployed'
    required: false
  image:
    description: 'Docker image to be deployed'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'